Allow custom jar user features to be installed
paketo-buildpacks/open-liberty pull request #23
Opened 2022-01-04 14:06 UTC by hibell

## Summary

This change allows custom Liberty user features (jars only for now) to be loaded similarly via an external configuration package (similar to how Tomcat does it).

## Use Cases

Users with customer features can now load their features jars into Liberty.

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2022-01-07 20:55 UTC, dmikusa-pivotal commented on README.md
> +| `$BP_OPENLIBERTY_EXT_CONF_URI`    | The download URI of the external configuration package.
This is missing `BP_OPENLIBERTY_EXT_CONF_VERSION`.

2022-01-07 20:55 UTC, dmikusa-pivotal commented on openliberty/base.go
> +func (b Base) writeDependencySBOM(layer libcnb.Layer, syftArtifacts []sbom.SyftArtifact) error {
This also seems to be adding at least partial SBOM support. That's a good thing, but I'm wondering if that was intentional? In the interest of a smaller more focused PR, did you try without it?

If it's too much of a pain, we can keep it like this. We need to add SBOM support before we go 1.0, so it has to happen at some point.

2022-01-07 21:50 UTC, hibell commented on README.md
> +| `$BP_OPENLIBERTY_EXT_CONF_URI`    | The download URI of the external configuration package.
Thanks for catching that.

2022-01-07 21:56 UTC, hibell commented on openliberty/base.go
> +func (b Base) writeDependencySBOM(layer libcnb.Layer, syftArtifacts []sbom.SyftArtifact) error {
Good point. I'll remove it for now and we can add in a separate PR.

2022-01-12 15:23 UTC, dmikusa-pivotal requested changes

2022-01-12 15:23 UTC, dmikusa-pivotal commented on helper/linker.go
> +	}
Can this be moved to after `ReadFeatureDescriptor` and `if len(featureDescriptor.Features) <= 0`?

It's a minor thing, but this will add a folder for features regardless of if there are actually any features. If it's possible, we should avoid creating that folder until after we're sure that there are enabled features.

2022-01-12 15:23 UTC, dmikusa-pivotal commented on helper/linker.go
> +		}
Is this or some part of this code we could push out to a method on the Feature struct? So...

```go
for _, feature := range featureDescriptor.Features {
    if err := feature.Link(); err != nil { ... }
    if err := feature.Enable(); err != nil { ... }
}
```

That would help as it would be easier to test this functionality.

2022-01-12 15:23 UTC, dmikusa-pivotal commented on helper/linker.go
> +	if len(featureDescriptor.Features) <= 0 {
I think we need a test case where len > 0. The current test cases aren't going to have any features, so everything below this won't be exercised in the present tests.

2022-01-12 15:23 UTC, dmikusa-pivotal commented on README.md
> +After creating the feature descriptor, tar and gzip the `feature.toml` and `features` directory so that it tar has the
```suggestion
After creating the feature descriptor, tar and gzip the `feature.toml` and `features` directory so that it has the
```

2022-01-12 15:23 UTC, dmikusa-pivotal commented on README.md
> +contents similar to the following, and upload it somewhere it can be served via HTTP.
Technically you can do HTTP (preferrably HTTPS) or `file://`, with the latter, you'd need to volume mount that path into the container image. So if you volume map `/features` into the container, you could use `file:///features/liberty-conf.tar.gz` as the `BP_OPENLIBERTY_EXT_CONF_URI`. 

I'm not 100% sure if you want to mention/use that here, but I thought I'd point it out as an option.

2022-01-12 15:23 UTC, dmikusa-pivotal commented on README.md
> +pack build --path myapp --env BP_OPENLIBERTY_EXT_CONF_URI=http://example.com/liberty-conf.tar.gz --env BP_OPENLIBERTY_EXT_CONF_VERSION=1.0.0 myapp
Does the example need `BP_OPENLIBERTY_EXT_CONF_SHA256`?

2022-01-26 18:12 UTC, dmikusa-pivotal requested changes
Just a couple of quick formatting changes.

2022-01-26 19:45 UTC, dmikusa-pivotal approved these changes

2022-01-26 19:45 UTC, merged