Add packaged server support
paketo-buildpacks/open-liberty pull request #51
Opened 2022-02-02 07:05 UTC by hibell

## Summary

Allow users to build Liberty server directory or from a packaged Liberty server.

## Use Cases

Users that want to use their existing Liberty server config and apps.

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2022-02-11 21:21 UTC, dmikusa-pivotal requested changes

2022-02-11 21:21 UTC, dmikusa-pivotal commented on openliberty/detect.go
> +	DefaultServerName = "defaultServer"
I feel like this needs to be configurable now. For the application deployment scenario, one doesn't really care what the server name is, but if I'm pushing a packaged server or pushing a wlp directory, the server name is embedded in what I push and I might not set it to be defaultServer.

At least that was my experience when testing. I am admittedly not familiar with Open Liberty though, so perhaps this is a solid enough convention that someone would typically call their server defaultServer.

2022-02-11 21:21 UTC, dmikusa-pivotal commented on openliberty/detect.go
> +		util.FileExists(filepath.Join(context.Application.Path, "wlp", "usr", "servers", DefaultServerName, "server.xml"))
Looking through the code more and I realize that changing this path might be tricky. I see the `server package` command creates a zip that has this leading `wlp` folder. 

Is my test above a valid use case we're trying to support? I had assumed that this is what you'd meant by `Building from a Liberty Server Installation Directory` in the README. If that's not the intent, please let me know.

If it is the intent, then the buildpack should probably check both paths with and without the leading `wlp/`.

2022-02-17 16:39 UTC, hibell commented on openliberty/build.go
> +	if installType == openLibertyInstall {
I tried to simplify the logic and make it easier to read by refactoring the code into separate functions. I like your idea of the `InstallType` interface but I'd like to think about this some more first  before adding.

2022-02-17 19:01 UTC, hibell commented on openliberty/detect.go
> +		})
Rationale was to follow similar behavior as OL did when users supply a compiled artifact. If the compiled artifact is not a valid JVM application package, the `jvm-application-package` plan would be unmet by OL and need to be supplied by some other buildpack.

I wanted to do the same check on the packaged server where the build would fail due to unmet requirements if the packaged server did not include an application (e.g. by accident) and to allow a subsequent buildpack to provide one similarly to how OL does it currently.

If you do not think this is necessary or does not make any sense, I am okay with removing it.

2022-02-17 19:12 UTC, hibell commented on openliberty/detect.go
> +		util.FileExists(filepath.Join(context.Application.Path, "wlp", "usr", "servers", DefaultServerName, "server.xml"))
Agreed that it is a bit awkward. I think checking both for `wlp/usr` and just `usr` makes sense.

2022-02-24 21:14 UTC, dmikusa-pivotal commented on openliberty/detect.go
> +		})
Ok, gotcha. That sounds good.

2022-02-24 21:14 UTC, merged