first pass at renaming repo
paketo-buildpacks/open-liberty pull request #71
Opened 2022-02-25 16:10 UTC by kevin-ortega

## Summary

Renaming open-liberty repo to liberty repo to more accurately reflect what the buildpack contributes. 

## Use Cases

The buildpack can provide open liberty and WebSphere liberty UBI images and we will eventually add WebSphere support to the ubuntu stack.  

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2022-02-25 19:36 UTC, dmikusa-pivotal requested changes
You would also need to rename the top-level directory `openliberty` to `liberty`.

2022-02-25 19:36 UTC, dmikusa-pivotal commented on README.md
> +The Paketo Open Buildpack is a Cloud Native Buildpack that contributes Open Liberty or WebSphere Liberty for Java EE support.
```suggestion
The Paketo Liberty Buildpack is a Cloud-Native Buildpack that contributes Open Liberty or WebSphere Liberty for Java EE support.
```

2022-02-25 19:36 UTC, dmikusa-pivotal commented on cmd/buildpack/main.go
> +	"github.com/paketo-buildpacks/liberty/openliberty"
```suggestion
	"github.com/paketo-buildpacks/liberty/liberty"
```

2022-02-25 19:36 UTC, dmikusa-pivotal commented on helper/linker.go
> +	"github.com/paketo-buildpacks/liberty/openliberty"
```suggestion
	"github.com/paketo-buildpacks/liberty/liberty"
```

2022-02-25 19:36 UTC, dmikusa-pivotal commented on helper/linker.go
> +		layerDir = "/layers/paketo-buildpacks_liberty/open-liberty-runtime"
Not sure about this one? I don't like the fact that we have this line hard coded here. I would honestly prefer if we removed this line & just fail if `BPI_OL_RUNTIME_ROOT` is not set. That should always be set by the buildpack. I think it's OK to fail if it's not set.

2022-02-25 19:36 UTC, dmikusa-pivotal commented on helper/linker.go
> +		f.BaseLayerPath = "/layers/paketo-buildpacks_liberty/base"
Same as the previous coment.

I don't like that the path is hard coded. We should rely on that env variable being set or fail. The buildpack should always set it, or something is really wrong and we should be failing.

2022-02-25 19:36 UTC, dmikusa-pivotal commented on openliberty/base_test.go
> +	"github.com/paketo-buildpacks/liberty/openliberty"
```suggestion
	"github.com/paketo-buildpacks/liberty/liberty"
```

2022-02-25 19:36 UTC, dmikusa-pivotal commented on openliberty/build.go
>  	dep, err := dr.Resolve(fmt.Sprintf("open-liberty-runtime-%s", profile), version)
I think this needs to change. It should match the id of the dependencies configured in buildpack.toml.

2022-02-25 19:36 UTC, dmikusa-pivotal commented on openliberty/build_test.go
> +	"github.com/paketo-buildpacks/liberty/openliberty"
```suggestion
	"github.com/paketo-buildpacks/liberty/liberty"
```

2022-02-25 19:36 UTC, dmikusa-pivotal commented on openliberty/detect_test.go
> +	"github.com/paketo-buildpacks/liberty/openliberty"
```suggestion
	"github.com/paketo-buildpacks/liberty/liberty"
```

2022-02-25 19:36 UTC, dmikusa-pivotal commented on openliberty/distribution_test.go
> +	"github.com/paketo-buildpacks/liberty/openliberty"
```suggestion
	"github.com/paketo-buildpacks/liberty/liberty"
```

2022-02-25 19:36 UTC, dmikusa-pivotal commented on openliberty/feature_test.go
> +	"github.com/paketo-buildpacks/liberty/openliberty"
```suggestion
	"github.com/paketo-buildpacks/liberty/liberty"
```

2022-02-25 21:11 UTC, dmikusa-pivotal commented
There are also a number of places where we use `OL` short for open-liberty. We should change those to just `liberty`. I think it's mainly in env variable names like `BPI_OL_...`.

2022-02-27 19:59 UTC, kevin-ortega commented on openliberty/build.go
>  	dep, err := dr.Resolve(fmt.Sprintf("open-liberty-runtime-%s", profile), version)
Yes, this will need to change when we add websphere liberty in buildpack.toml.  For now, we just have open-liberty.

2022-02-28 22:06 UTC, kevin-ortega commented
@dmikusa-pivotal I don't think the 2 failing actions are something I can fix?

2022-03-02 01:38 UTC, dmikusa-pivotal approved these changes
OK, tests are passing. I'm going to merge this and rename the repo. If we've missed anything, we can adjust in a subsequent PR. I think it'll be easier to validate after the repo is renamed.

2022-03-02 01:39 UTC, merged