Add `BP_INSTALL_TYPE` to configure install type
paketo-buildpacks/open-liberty pull request #9
Opened 2021-11-30 18:50 UTC by hibell

## Summary
The proposed change is to add `BP_INSTALL_TYPE` option to configure which Liberty runtime we use. The value defaults to `ol` which just pulls Open Liberty archive as it did originally.

Three other runtime options were added:
* `wlp` (not actually implemented yet): Download and use WebSphere Liberty runtime.
* `ol-stack` Do not contribute any Liberty runtime in the buildpack. Instead use the OL runtime provided in the stack (requires an OL stack run image)
* `wlp-stack` Do not contribute any Liberty runtime in the buildpack. Instead use the WLP runtime provided in the stack (requires an WLP stack run image)

Note: Two stack options were necessary since the OL and WLP use different root paths for their runtime. If we can determine which stack run image is being used during build, maybe we can combine both options to just `stack`.

## Use Cases
Allows user to configure which runtime they'd like to use. The stack options allow users that are dependent on the existing OL / WLP images to use the Open Liberty CNB.

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement. (**IN PROGRESS**)
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2021-12-01 17:59 UTC, dmikusa-pivotal commented
@hibell - OK, first thing. You'll need to click the link above and satisfy the EasyCLA bot. Not sure if you're covered under a corp contributor agreement, you might need to check that. I believe the instructions walk you through all of that.

I took a look through the rest. There's a number of changes so it'll take a little time for me to go through them. I'll try to get some more feedback for you shortly. Thanks for the PR!

2021-12-03 14:41 UTC, hibell commented
@dmikusa-pivotal I am hitting a snag with EasyCLA and IBM that I'll hopefully have resolved soon. While I am waiting for that issue to be resolved, are there any changes you would like to be made? We have a client that is interested in trying the buildpack soon so we were hoping to get feedback as soon as possible. Thanks.

2021-12-10 22:01 UTC, dmikusa-pivotal commented
Question:

>The proposed change is to add BP_INSTALL_TYPE option to configure which Liberty runtime we use.

Do you see this option as something end-users will be configuring? Env variables typically work best for end-user facing config.

I ask because you can also configure things like this through the buildplan. The buildplan typically works best though if this is something you would set based on input from another buildpack.

It sounds like the former, but just want to confirm. Thanks

2021-12-10 22:03 UTC, dmikusa-pivotal commented
One more question: 

For the `*-stack` options, what about just having a "none" option. Where that just tells the buildpack to not install the dependency. It would still be able to do logic/contribute config. If it's `none` we'd just need to do something to look up the type, possibly by checking for the presence of files in certain locations? It sounds like the stacks have standard locations, so that might work?

2021-12-13 16:16 UTC, hibell commented
> Question:
> 
> > The proposed change is to add BP_INSTALL_TYPE option to configure which Liberty runtime we use.
> 
> Do you see this option as something end-users will be configuring? Env variables typically work best for end-user facing config.
> 
> I ask because you can also configure things like this through the buildplan. The buildplan typically works best though if this is something you would set based on input from another buildpack.
> 
> It sounds like the former, but just want to confirm. Thanks

The `BP_OPENLIBERTY_INSTALL_TYPE` (formerly `BP_INSTALL_TYPE`) would need to be configured during the build so that the OL buildpack won't contribute another runtime. Would a stack be able to influence the build configuration via a buildplan?

> For the *-stack options, what about just having a "none" option. Where that just tells the buildpack to not install the dependency. It would still be able to do logic/contribute config. If it's none we'd just need to do something to look up the type, possibly by checking for the presence of files in certain locations? It sounds like the stacks have standard locations, so that might work?

Yes, the runtime roots are at certain locations depending on the stack being used:
* `ol-stack` runtime root = `/opt/ol/wlp`
* `wlp-stack` runtime root = `/opt/ibm/wlp`

However, since both OL and WLP stacks use a wrapper script to configure the server, we needed to edit the run command and its arguments (see [build.go L108](https://github.com/paketo-buildpacks/open-liberty/pull/9/files#diff-8ebf8e4022c75bd1e04be84ae6547c36997b017597821affc003b898cf71f64cR108)).

The run commands for the different scenarios would be:
* `ol` and `wlp` run command = `server run defaultServer`
* `ol-stack` run command = `/opt/ol/helpers/runtime/docker-server.sh /opt/ol/wlp/bin/server run defaultServer`
* `wlp-stack` run command = `/opt/ibm/helpers/runtime/docker-server.sh /opt/ibm/wlp/bin/server run defaultServer`

Instead of baking in the absolute paths for the command, we could edit the `PATH` in the run stacks to include `<runtime-root>/helpers` and `<runtime-root>/wlp/bin` so that we could simplify the `*-stack` options to just `none`. I had originally wanted to use absolute paths though to make it obvious what runtime is actually being used.

2021-12-13 18:13 UTC, dmikusa-pivotal commented
>The BP_OPENLIBERTY_INSTALL_TYPE (formerly BP_INSTALL_TYPE) would need to be configured during the build so that the OL buildpack won't contribute another runtime. Would a stack be able to influence the build configuration via a buildplan?

It really depends on what is making the decision about the install type.

If a user is going to make that determination, i.e. you want the user experience to be such that when performing a build the user needs to say what type they want (or accept the default), then an env variable works.

If you want to try and do some fancier auto-detection by the buildpack. If there are files that a user might push which might indicate the type we should use, or if the user attaches a service binding (perhaps to provide a license key?) then that's something you'd typically signal through the buildplan.

It doesn't have to be exclusive either. You can have both. It's just a little extra work. With both, typically the value the user enters would override everything, and auto-detection would override the static default.

We can also add things like this later too. Just wanted to mention the possibility and see what you think.

2021-12-13 18:21 UTC, dmikusa-pivotal commented
>Instead of baking in the absolute paths for the command, we could edit the PATH in the run stacks to include <runtime-root>/helpers and <runtime-root>/wlp/bin so that we could simplify the *-stack options to just none. I had originally wanted to use absolute paths though to make it obvious what runtime is actually being used.

In general, we try to put stuff on the PATH. It makes things easier for folks and tends to avoid the inevitable question of "why is `xyz` command not found?".

Buildpacks have a concept of process types, which can be given a name. To your point about making it obvious which type of server is running, I think we could use process types for that. When you write the process type, you can give it a name. We often just use `web`, but that name can be anything and can be different based on the command you write.

So you could conditionally write a process types of `open-liberty`, `open-liberty-stack` or `web-sphere-stack` (or whatever you want to call them). It doesn't matter what you name them so long as you tag one as "default". That's the command that will be run when the container starts.

By doing this, someone could run `pack inspect <img>` and it would show them the process type, which would have the name to indicate the specific server type being used.

Another possible way to handle this is with SBOM. The buildpack can write SBOM entries that can be used as a bill of materials to see what is in the container. By default, the buildpack will write those for dependencies that it installs but you could make it write them for the stack-provided dependencies too, if you wanted.

2021-12-13 19:27 UTC, dmikusa-pivotal requested changes

2021-12-13 19:27 UTC, dmikusa-pivotal commented on buildpack.toml
> +
I can't comment on it, but lines 58 and 60 below need to be updated. That variable was changed & there's a suggestion above for the description.

2021-12-13 19:27 UTC, dmikusa-pivotal commented on helper/linker.go
> +	return nil, nil
```suggestion
	return map[string]string{}, nil
```

I don't think it matters a ton, but from a style standpoint, we try to return empty values.

2021-12-13 19:27 UTC, dmikusa-pivotal commented on helper/linker.go
> +		return nil, fmt.Errorf("error during configuration: %w", err)
```suggestion
		return map[string]string{}, fmt.Errorf("error during configuration: %w", err)
```

Same, just trying to keep styles consistent.

2021-12-13 19:27 UTC, dmikusa-pivotal commented on helper/linker.go
> +		return nil, fmt.Errorf("error during configuration: %w", err)
```suggestion
		return nil, fmt.Errorf("unable to configure\n%w", err)
```

More style stuff. We try to use `unable to ...` with messages. Not my choice, but for consistency, we also use `\n` before printing other errors.

I don't think some of this came from your commit, but using it as a chance to refactor. Pardon the extra noise.

2021-12-13 19:27 UTC, dmikusa-pivotal commented on helper/linker.go
> +		return fmt.Errorf("error resolving bindings: %w", err)
```suggestion
		return fmt.Errorf("unable to resolve bindings\n%w", err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on helper/linker.go
> +				return fmt.Errorf("error replacing server.xml: %w", err)
```suggestion
				return fmt.Errorf("unable to replace server.xml\n%w", err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on helper/linker.go
> +				return fmt.Errorf("error replacing bootstrap.properties: %w", err)
```suggestion
				return fmt.Errorf("unable to replace bootstrap.properties\n%w", err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on helper/linker.go
> +		return fmt.Errorf("error symlinking application to '%v':\n%w", linkPath, err)
```suggestion
		return fmt.Errorf("unable to symlink application to '%v':\n%w", linkPath, err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on helper/linker.go
> +		return fmt.Errorf("error looking for file '%v': %w", from, err)
```suggestion
		return fmt.Errorf("unable to find file '%v'\n%w", from, err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on helper/linker.go
> +		return fmt.Errorf("error deleting original file '%v': %w", from, err)
```suggestion
		return fmt.Errorf("unable to delete original file '%v'\n%w", from, err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on helper/linker.go
> +		return fmt.Errorf("error linking file from '%v' to '%v': %w", from, to, err)
```suggestion
		return fmt.Errorf("unable to symlink file from '%v' to '%v'\n%w", from, to, err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on helper/linker.go
> +		return ServerConfig{}, fmt.Errorf("unable to open server.xml '%v': %w", configPath, err)
```suggestion
		return ServerConfig{}, fmt.Errorf("unable to open server.xml '%v'\n%w", configPath, err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on helper/linker.go
> +		return ServerConfig{}, fmt.Errorf("unable to read server.xml '%v': %w", configPath, err)
```suggestion
		return ServerConfig{}, fmt.Errorf("unable to read server.xml '%v'\n%w", configPath, err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on helper/linker.go
> +		return ServerConfig{}, fmt.Errorf("unable to unmarshal server.xml: '%v': %w", configPath, err)
```suggestion
		return ServerConfig{}, fmt.Errorf("unable to unmarshal server.xml: '%v'\n%w", configPath, err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on openliberty/base.go
> +			return libcnb.Layer{}, fmt.Errorf("unable to contribute config templates: %w", err)
```suggestion
			return libcnb.Layer{}, fmt.Errorf("unable to contribute config templates\n%w", err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on openliberty/base.go
> +		return fmt.Errorf("could not create config template directory '%v': %w", templateDir, err)
```suggestion
		return fmt.Errorf("unable to create config template directory '%v'\n%w", templateDir, err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on openliberty/base.go
> +		return fmt.Errorf("could not read source directory: %w", err)
```suggestion
		return fmt.Errorf("unable to read source directory\n%w", err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on openliberty/base.go
> +				return fmt.Errorf("could not open source template file '%v': %w", srcPath, err)
```suggestion
				return fmt.Errorf("unable to open source template file '%v'\n%w", srcPath, err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on openliberty/base.go
> +				return fmt.Errorf("could not copy template from '%v' -> '%v': %w", srcPath, destPath, err)
```suggestion
				return fmt.Errorf("unable to copy template from '%v' -> '%v'\n%w", srcPath, destPath, err)
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on openliberty/build.go
> +	if installType == "ol" || installType == "wlp" {
These types should be turned into const strings.

2021-12-13 19:27 UTC, dmikusa-pivotal commented on openliberty/build.go
> +	} else if installType == "ol-stack" || installType == "wlp-stack" {
As mentioned in the other comment, if you `os.Stat` here an look for the directories, the buildpack should be able to detect at least these two types.

Something like:

```
if ol then install open liberty
if wlp then install web sphere liberty
if none then
  if os.Stat `/opt/ol` is Directory then config process type only
  if os.Stat `/opt/ibm` is Directory then config process type only
  else error, unable to find server in stack image
else unable to process install type `foo`
```

2021-12-13 19:27 UTC, dmikusa-pivotal commented on openliberty/build.go
> +			Arguments: args,
All of the process types should set `Direct: true`. Using `Direct: false`, which is the default because of Go defaults, is being deprecated.

What this means, "direct", is that the process you specify will be run without a shell. I think that should be OK here, because it's going to run your shell script, which will execute with the interpreter set in your script shebang. If this causes issues for some reason, you could set the command to `bash` and args to `["-c", ...everything else...]` and run the script in bash (or whatever shell you want that way.

2021-12-13 19:31 UTC, dmikusa-pivotal commented on openliberty/build.go
> +			Arguments: args,
Oh, and `Type` is basically the name. This is what I was referring to in the other comment. If you set `Type: "open-liberty"` or `Type: "web-sphere-liberty"` it should be pretty clear in the tooling what is being executed.

You only have one process type and the default is true, so that'll run no matter what you set for the type.

2021-12-14 16:57 UTC, hibell commented on README.md
> +* At launch time, symlink `<APPLICATION_ROOT>` to `${BPI_OL_RUNTIME_ROOT}/usr/servers/defaultServer/apps/<APPLICATION_ROOT_BASENAME>`.
Yeah, that should be enough. Liberty users should be familiar with the defaultServer.

2021-12-14 17:03 UTC, hibell commented on README.md
> +All of these defaults can be overridden by setting the appropriate properties found in Open Liberty's [documentation](https://openliberty.io/docs/21.0.0.11/log-trace-configuration.html). They can be
Yeah. https://openliberty.io/docs/latest/log-trace-configuration.html redirects to the latest version. I will update.

2021-12-14 17:07 UTC, hibell commented on buildpack.toml
> +
Doh -- bad merge. Thanks for catching that :)

2021-12-17 21:07 UTC, dmikusa-pivotal approved these changes
This looks good to me. Thanks for the PR!

2021-12-17 21:07 UTC, merged